name: Build and publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build Kernel package
        run: |
          pacman -Syu --needed --noconfirm sudo
          pacman -U --noconfirm https://gist.githubusercontent.com/love4taylor/47e6eea5dec795413251adf4ed286ec9/raw/b8d7ce82b7d49787c76fff28f739d24197856859/pahole-1:1.26-2-x86_64.pkg.tar.zst
          sed -i "s|#MAKEFLAGS=.*|MAKEFLAGS=-j$(nproc)|" /etc/makepkg.conf
          useradd -m user || true
          passwd -d user
          printf 'user ALL=(ALL) ALL\n' | tee -a /etc/sudoers
          cp -r $GITHUB_WORKSPACE/* /home/user
          chown -R user /home/user
          sudo -u user bash -c 'gpg2 --locate-keys torvalds@kernel.org gregkh@kernel.org nathan@kernel.org'
          sudo -u user bash -c 'cd ~;makepkg -s --noconfirm'
      - name: Upload Kernel Package
        uses: actions/upload-artifact@v4
        with:
          name: pkg
          path: /home/user/*.pkg.tar.zst
      - name: Release Kernel Package
        uses: ncipollo/release-action@v1
        with:
          artifacts: "/home/user/*.pkg.tar.zst"
